---

- name: Install pip package for encryption
  pip:
    name:
      - passlib
- name: Add my user
  user:
    name: "{{ username }}"
    password: "{{ 'crest108dark360' | password_hash }}"
    comment: Finn St John
    state: present
    shell: /usr/bin/zsh
- name: Allow passwordless sudo
  copy:
    src: "{{ username }}"
    dest: /etc/sudoers.d/
- name: Wallpaper
  block:
    - name: Create wallpapers directory
      file:
        path: /home/{{ username }}/Pictures
        state: directory
    - name: Copy wallpaper file
      copy:
        src: wallpaper.png
        dest: /home/{{ username }}/Pictures/
    # TODO: implement this for real
    # - name: Set wallpaper
    #   dconf:
    #     key: /org/gnome/desktop/background/picture-uri
    #     value: /home/{{ username }}/Pictures/wallpaper.png
    - name: Add wallpaper message to dump file
      lineinfile:
        line: '* **Set the wallpaper** ---- gsettings set org.gnome.desktop.background picture-uri "~/Pictures/wallpaper.png"\n'
        path: "{{ dump_file }}"
# TODO: implement this for real also
# - name: Set cursor theme
#   dconf:
#     key: /org/gnome/desktop/interface/cursor-theme
#     value: macOS-BigSur
- name: Add cursor theme message to dump file
  lineinfile:
    line: '* **Set the cursor theme** ---- gsettings set org.gnome.desktop.interface cursor-theme "macOS-BigSur"\n'
    path: "{{ dump_file }}"
