---

- name: Install pip package for encryption
  pip:
    name:
      - passlib
- name: Add my user
  user:
    name: finn
    password: "{{ 'crest108dark360' | password_hash }}"
    comment: Finn St John
    state: present
- name: Allow passwordless sudo
  copy:
    src: finn
    dest: /etc/sudoers.d/
