---

- name: Update all packages
  dnf:
    name: "*"
    state: latest

- name: Install packages i fw
  dnf:
    state: present
    name:
      - google-noto*
      - bat
      - htop
      - NetworkManager
      - NetworkManager-tui
      - vim
      - git
      - ncdu
      - tldr
      - golang
      - gammastep
      - exa
      - feh
      - ansible
      - VirtualBox
      - alacritty
      - task
      - gnome-extensions-app
      - rubygem-sass
      - nodejs
      - arp-scan
      - kubectl
      - dnf-plugins-core
      - vagrant
      - codium
      - zsh
      - wget
      - sqlite3
      - acl
      - yq

- name: Install minikube
  block:
    - get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
        dest: /tmp/
        mode: 0644
    - dnf:
        name: /tmp/minikube-latest.x86_64.rpm
        state: present
        disable_gpg_check: true

- name: Remove packages ion fw
  dnf:
    state: absent
    name:
      - simple-scan
      - gnome-software
      - gnome-calculator
      - gnome-calendar
      - gnome-contacts
      - gnome-maps
      - gnome-text-editor
      - gnome-tour
      - gnome-weather
      - gnome-disk-utility
      - gnome-boxes
      - gnome-photos
      - gnome-remote-desktop
      - gnome-connections
      - gnome-user-docs
      - gnome-user-share
      - gnome-backgrounds
      - gnome-clocks
      - libreoffice-core
      - yelp
      - rhythmbox
      - cheese
      - evince
      - evince-djvu
      - evince-libs
      - baobab
      - eog
      - gnome-font-viewer
      - gnome-characters
