---

- name: Install packages
  dnf:
    state: present
    name:
      - bat
      - htop
      - NetworkManager
      - NetworkManager-tui
      - vim
      - git
      - ncdu
      - tldr
      - golang
      - gammastep
      - exa
      - feh
      - vagrant
      - ansible