---

- name: Install home directory configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/skel
  loop:
    - .bashrc
    - .inputrc
    - .vimrc

- name: Install gammastep config file
  copy:
    src: gammastep.conf
    dest: /etc/skel/.config/