---

- name: Install home directory configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/skel
  loop:
    - .bashrc
    - .inputrc
    - .vimrc

- name: Install XDG_CONFIG_DIR files or whatever 
  copy:
    src: "{{ item }}"
    dest: /etc/skel/.config/
  loop:
    - alacritty.yml
    - gammastep.conf
