---

- name: Install home directory configuration files
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}
  loop:
    - .bashrc
    - .inputrc
    - .vimrc
    - .zshrc

- name: Install XDG_CONFIG_DIR files or whatever 
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/
  loop:
    - alacritty.yml
    - gammastep.conf
