---

- name: Install home directory configuration files
  become_user: "{{ username }}"
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}
  loop:
    - .inputrc
    - .vimrc
    - .gitconfig

- name: Template home directory configuration files, if applicable
  become_user: "{{ username }}"
  block:
    - template:
        src: .bashrc.j2
        dest: /home/{{ username }}/.bashrc
    - template:
        src: .zshrc.j2
        dest: /home/{{ username }}/.zshrc

- name: Install XDG_CONFIG_DIR files or whatever
  become_user: "{{ username }}"
  copy:
    src: "{{ item }}"
    dest: /home/{{ username }}/.config/
  loop:
    - alacritty.toml
    - gammastep.conf
