---

- name: Install python-related packages
  dnf:
    state: present
    name:
      - python
      - python-launcher

- name: Install Jupyter Notebook
  pip:
    name: jupyter-notebook
    state: present