---

- name: Install python-related packages
  dnf:
    state: present
    name:
      - python
      - python-launcher
      - python3-pip

- name: Install Jupyter Notebook
  pip:
    name: notebook
    state: present