---

- name: Add sign in to firefox message
  set_fact:
    dump_file_content: "{{ dump_file_content + ['* Remember to sign into firefox!'] }}"

- name: Add firefox extensions message
  set_fact:
    dump_file_content: "{{ dump_file_content + ['* Remember to install these **Firefox** extensions: GNOME Shell Integration'] }}"

- name: Install user preferences file
  become_user: "{{ username }}"
  copy:
    src: user.js
    dest: home/{{ username }}/.mozilla/