---

- name: Install Node and NPM
  dnf:
    name: nodejs

# NEVER install things globally here, I did this once, but I think it's cleaner
# to just use `npx <command>`, which can be run without installing the global
# package.
